CREATE TABLE public.newsletter ( id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, full_name character varying NOT NULL, email character varying NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now(), created_by character varying NOT NULL, updated_at timestamp with time zone, updated_by character varying, deleted_at timestamp with time zone, deleted_by character varying, is_deleted boolean NOT NULL DEFAULT false, CONSTRAINT newsletter_pkey PRIMARY KEY (id) );

CREATE TABLE public.numbering ( module character varying NOT NULL, number bigint NOT NULL, CONSTRAINT numbering_pkey PRIMARY KEY (module) );

CREATE TABLE public.user_role ( id uuid NOT NULL DEFAULT gen_random_uuid(), name character varying NOT NULL DEFAULT ''::character varying, code character varying NOT NULL DEFAULT ''::character varying UNIQUE, created_at timestamp with time zone NOT NULL, created_by character varying DEFAULT ''::character varying, update_at timestamp with time zone, updated_by character varying, deleted_at timestamp with time zone, deleted_by character varying, is_deleted boolean NOT NULL DEFAULT false, CONSTRAINT user_role_pkey PRIMARY KEY (id) );

CREATE TABLE public."user" ( id uuid NOT NULL DEFAULT gen_random_uuid(), full_name character varying NOT NULL DEFAULT ''::character varying, email character varying NOT NULL DEFAULT ''::character varying, password character varying NOT NULL DEFAULT ''::character varying, role_code character varying NOT NULL DEFAULT gen_random_uuid(), created_at timestamp with time zone NOT NULL DEFAULT now(), created_by character varying DEFAULT ''::character varying, updated_at timestamp with time zone, updated_by character varying, deleted_at timestamp with time zone, deleted_by character varying, is_deleted boolean DEFAULT false, CONSTRAINT user_pkey PRIMARY KEY (id), CONSTRAINT user_role_code_fkey FOREIGN KEY (role_code) REFERENCES public.user_role(code) );

CREATE TABLE public.product ( id uuid NOT NULL DEFAULT gen_random_uuid(), name character varying NOT NULL, price numeric NOT NULL, description character varying NOT NULL DEFAULT ''::character varying, image_file_name character varying NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now(), created_by character varying NOT NULL, updated_at timestamp with time zone, updated_by character varying, deleted_at timestamp with time zone, deleted_by character varying, is_deleted boolean DEFAULT false, CONSTRAINT product_pkey PRIMARY KEY (id) );

CREATE TABLE public.order_status ( id uuid NOT NULL DEFAULT gen_random_uuid(), name character varying NOT NULL, code character varying NOT NULL UNIQUE, created_at timestamp with time zone NOT NULL DEFAULT now(), created_by character varying NOT NULL, updated_at timestamp with time zone, updated_by character varying, deleted_at timestamp with time zone, deleted_by character varying, is_deleted boolean DEFAULT false, CONSTRAINT order_status_pkey PRIMARY KEY (id) );

CREATE TABLE public."order" ( id uuid NOT NULL DEFAULT gen_random_uuid(), number character varying NOT NULL, user_id uuid NOT NULL DEFAULT gen_random_uuid(), order_status_code character varying NOT NULL, user_full_name character varying NOT NULL, address character varying NOT NULL, phone_number character varying NOT NULL, notes character varying, total numeric NOT NULL, expired_at timestamp with time zone NOT NULL, created_at timestamp with time zone NOT NULL DEFAULT now(), created_by character varying NOT NULL, updated_at timestamp with time zone, updated_by character varying, deleted_at timestamp with time zone, deleted_by character varying, is_deleted boolean DEFAULT false, xendit_invoice_id character varying, xendit_invoice_url character varying, xendit_paid_at timestamp with time zone, xendit_payment_method character varying, xendit_payment_channel character varying, CONSTRAINT order_pkey PRIMARY KEY (id), CONSTRAINT order_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id), CONSTRAINT order_order_status_code_fkey FOREIGN KEY (order_status_code) REFERENCES public.order_status(code) );

CREATE TABLE public.order_item ( id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, product_id uuid NOT NULL DEFAULT gen_random_uuid(), product_name character varying NOT NULL, product_image_file_name character varying NOT NULL, product_price numeric NOT NULL, quantity bigint NOT NULL, order_id uuid, created_at timestamp with time zone NOT NULL DEFAULT now(), created_by character varying NOT NULL, updated_at timestamp with time zone, updated_by character varying, deleted_at timestamp with time zone, deleted_by character varying, is_deleted boolean DEFAULT false, CONSTRAINT order_item_pkey PRIMARY KEY (id), CONSTRAINT order_item_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id), CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES public."order"(id) );

CREATE TABLE public.user_cart ( id bigint GENERATED ALWAYS AS IDENTITY NOT NULL, product_id uuid NOT NULL DEFAULT gen_random_uuid(), user_id uuid NOT NULL DEFAULT gen_random_uuid(), quantity bigint NOT NULL DEFAULT '0'::bigint, created_at timestamp with time zone NOT NULL DEFAULT now(), created_by character varying NOT NULL DEFAULT ''::character varying, updated_at timestamp with time zone, updated_by character varying, CONSTRAINT user_cart_pkey PRIMARY KEY (id), CONSTRAINT user_cart_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id), CONSTRAINT user_cart_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id) );